allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  vue-demi: true
  workerd: true
overrides:
  next: 16.2.6
  postcss: 8.5.15
  vite: 8.0.14
minimumReleaseAgeExclude:
  - next@16.1.7
  - vite@7.3.2
  - next@16.2.3
  - postcss@8.5.10
  - next@16.2.5
  - next@16.2.6
  - postcss@8.5.15
  - vite@7.3.3
  - vite@8.0.14
