import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const cwd = process.cwd();
const fonts = [
  {
    key: "GEIST_PIXEL_LINE_WOFF2_BASE64",
    path: "node_modules/geist/dist/fonts/geist-pixel/GeistPixel-Line.woff2",
  },
  {
    key: "GEIST_PIXEL_SQUARE_WOFF2_BASE64",
    path: "node_modules/geist/dist/fonts/geist-pixel/GeistPixel-Square.woff2",
  },
  {
    key: "GEIST_MONO_REGULAR_WOFF2_BASE64",
    path: "node_modules/geist/dist/fonts/geist-mono/GeistMono-Regular.woff2",
  },
];

const outFile = join(cwd, "src/lib/fonts.generated.ts");
const header = "// Generated by scripts/build-fonts.mjs. Do not edit manually.\n";
const lines = [header];

for (const font of fonts) {
  const file = join(cwd, font.path);
  const data = readFileSync(file).toString("base64");
  lines.push(`export const ${font.key} = ${JSON.stringify(data)};\n`);
}

writeFileSync(outFile, lines.join(""));
console.log(`Generated ${outFile}`);
